# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deep_trader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deep_trader.proto',
  package='deeptrader',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x65\x65p_trader.proto\x12\ndeeptrader\"R\n\x10GetCandleRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x12\n\ncycle_type\x18\x02 \x01(\t\x12\r\n\x05\x63ycle\x18\x03 \x01(\x05\x12\r\n\x05\x63ount\x18\x04 \x01(\x05\"p\n\nCandleData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\x05\x12\x0c\n\x04time\x18\x02 \x01(\x05\x12\x0c\n\x04open\x18\x03 \x01(\x05\x12\x0c\n\x04high\x18\x04 \x01(\x05\x12\x0b\n\x03low\x18\x05 \x01(\x05\x12\r\n\x05\x63lose\x18\x06 \x01(\x05\x12\x0e\n\x06volume\x18\x07 \x01(\x05\"N\n\x11GetCandleResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x0b\x63\x61ndle_data\x18\x02 \x03(\x0b\x32\x16.deeptrader.CandleData\"T\n\x12SubmitOrderRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x12\n\norder_type\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x05\"\x15\n\x13SubmitOrderResponse2\xa6\x01\n\nDeepTrader\x12H\n\tGetCandle\x12\x1c.deeptrader.GetCandleRequest\x1a\x1d.deeptrader.GetCandleResponse\x12N\n\x0bSubmitOrder\x12\x1e.deeptrader.SubmitOrderRequest\x1a\x1f.deeptrader.SubmitOrderResponseb\x06proto3'
)




_GETCANDLEREQUEST = _descriptor.Descriptor(
  name='GetCandleRequest',
  full_name='deeptrader.GetCandleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='deeptrader.GetCandleRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cycle_type', full_name='deeptrader.GetCandleRequest.cycle_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cycle', full_name='deeptrader.GetCandleRequest.cycle', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='deeptrader.GetCandleRequest.count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=115,
)


_CANDLEDATA = _descriptor.Descriptor(
  name='CandleData',
  full_name='deeptrader.CandleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='deeptrader.CandleData.date', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='deeptrader.CandleData.time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='open', full_name='deeptrader.CandleData.open', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='deeptrader.CandleData.high', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low', full_name='deeptrader.CandleData.low', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='close', full_name='deeptrader.CandleData.close', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='deeptrader.CandleData.volume', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=229,
)


_GETCANDLERESPONSE = _descriptor.Descriptor(
  name='GetCandleResponse',
  full_name='deeptrader.GetCandleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='deeptrader.GetCandleResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='candle_data', full_name='deeptrader.GetCandleResponse.candle_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=309,
)


_SUBMITORDERREQUEST = _descriptor.Descriptor(
  name='SubmitOrderRequest',
  full_name='deeptrader.SubmitOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='deeptrader.SubmitOrderRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_type', full_name='deeptrader.SubmitOrderRequest.order_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='deeptrader.SubmitOrderRequest.count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='deeptrader.SubmitOrderRequest.price', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=395,
)


_SUBMITORDERRESPONSE = _descriptor.Descriptor(
  name='SubmitOrderResponse',
  full_name='deeptrader.SubmitOrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=418,
)

_GETCANDLERESPONSE.fields_by_name['candle_data'].message_type = _CANDLEDATA
DESCRIPTOR.message_types_by_name['GetCandleRequest'] = _GETCANDLEREQUEST
DESCRIPTOR.message_types_by_name['CandleData'] = _CANDLEDATA
DESCRIPTOR.message_types_by_name['GetCandleResponse'] = _GETCANDLERESPONSE
DESCRIPTOR.message_types_by_name['SubmitOrderRequest'] = _SUBMITORDERREQUEST
DESCRIPTOR.message_types_by_name['SubmitOrderResponse'] = _SUBMITORDERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCandleRequest = _reflection.GeneratedProtocolMessageType('GetCandleRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCANDLEREQUEST,
  '__module__' : 'deep_trader_pb2'
  # @@protoc_insertion_point(class_scope:deeptrader.GetCandleRequest)
  })
_sym_db.RegisterMessage(GetCandleRequest)

CandleData = _reflection.GeneratedProtocolMessageType('CandleData', (_message.Message,), {
  'DESCRIPTOR' : _CANDLEDATA,
  '__module__' : 'deep_trader_pb2'
  # @@protoc_insertion_point(class_scope:deeptrader.CandleData)
  })
_sym_db.RegisterMessage(CandleData)

GetCandleResponse = _reflection.GeneratedProtocolMessageType('GetCandleResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCANDLERESPONSE,
  '__module__' : 'deep_trader_pb2'
  # @@protoc_insertion_point(class_scope:deeptrader.GetCandleResponse)
  })
_sym_db.RegisterMessage(GetCandleResponse)

SubmitOrderRequest = _reflection.GeneratedProtocolMessageType('SubmitOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITORDERREQUEST,
  '__module__' : 'deep_trader_pb2'
  # @@protoc_insertion_point(class_scope:deeptrader.SubmitOrderRequest)
  })
_sym_db.RegisterMessage(SubmitOrderRequest)

SubmitOrderResponse = _reflection.GeneratedProtocolMessageType('SubmitOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITORDERRESPONSE,
  '__module__' : 'deep_trader_pb2'
  # @@protoc_insertion_point(class_scope:deeptrader.SubmitOrderResponse)
  })
_sym_db.RegisterMessage(SubmitOrderResponse)



_DEEPTRADER = _descriptor.ServiceDescriptor(
  name='DeepTrader',
  full_name='deeptrader.DeepTrader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=421,
  serialized_end=587,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCandle',
    full_name='deeptrader.DeepTrader.GetCandle',
    index=0,
    containing_service=None,
    input_type=_GETCANDLEREQUEST,
    output_type=_GETCANDLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitOrder',
    full_name='deeptrader.DeepTrader.SubmitOrder',
    index=1,
    containing_service=None,
    input_type=_SUBMITORDERREQUEST,
    output_type=_SUBMITORDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEEPTRADER)

DESCRIPTOR.services_by_name['DeepTrader'] = _DEEPTRADER

# @@protoc_insertion_point(module_scope)
